v1 = int(input('Primeiro valor:'))
v2 = int(input('Segundo valor:'))
v3 = int(input('Terceiro valor:'))
print(f'O menor valor digitado foi {min(v1, v2, v3)}')
print(f'O maior valor digitado foi {max(v1, v2, v3)}')